# Generated by Django 4.1 on 2024-02-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0008_alter_speakers_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=50)),
                ('Cno', models.FloatField()),
                ('Cemail', models.EmailField(max_length=150)),
                ('detiles', models.TextField(blank=True, null=True)),
                ('Suite_number', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('B6', 'B6')], max_length=10)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Hold'), (2, 'accepted'), (3, 'rejected')], default=1)),
            ],
        ),
    ]
