# Generated by Django 4.1 on 2024-02-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0009_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Suite_number',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('B6', 'B6'), ('S1', 'S1'), ('C1', 'C1'), ('G1', 'G1')], max_length=10),
        ),
    ]
