# Generated by Django 4.1 on 2024-02-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0011_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gustis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.FloatField()),
                ('id_user', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
