# Generated by Django 4.1 on 2024-02-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0012_gustis'),
    ]

    operations = [
        migrations.AddField(
            model_name='gustis',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='Qr_code/'),
        ),
    ]
