# Generated by Django 4.1 on 2024-02-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0013_gustis_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='universty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
