# Generated by Django 5.0.2 on 2024-02-25 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0015_alter_project_options_remove_gustis_qr_gustis_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clouds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('descripe', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloudsGustis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('clouds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainProject.clouds')),
                ('gusti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainProject.gustis')),
            ],
        ),
    ]
