# Generated by Django 5.0.2 on 2024-02-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0016_clouds_cloudsgustis'),
    ]

    operations = [
        migrations.AddField(
            model_name='clouds',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
