# Generated by Django 5.0.2 on 2024-02-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0017_clouds_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gustis',
            name='phone',
            field=models.FloatField(unique=True),
        ),
    ]
