# Generated by Django 5.0.2 on 2024-02-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0018_alter_gustis_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.FloatField(unique=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
