# Generated by Django 5.0.2 on 2024-03-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0020_clouds_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouds',
            name='img',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
